export const CONFIG = {
  MAX_PHOTO_COUNT: 9,
  MAX_MESSAGE_LENGTH: 5000,
  OTP_LENGTH: 6,
  OTP_EXPIRY_SECONDS: 300,
  PASSWORD_MIN_LENGTH: 8,
  MAX_UPLOAD_SIZE_MB: 10,
  DEBOUNCE_DELAY: 300,
  TYPING_TIMEOUT: 3000,
  SESSION_REFRESH_THRESHOLD: 300000,
};
