export const ENDPOINTS = {
  AUTH: {
    REGISTER: '/auth/register',
    LOGIN: '/auth/login',
    OTP_SEND: '/auth/otp/send',
    OTP_VERIFY: '/auth/otp/verify',
    REFRESH: '/auth/refresh',
    LOGOUT: '/auth/logout',
    FORGOT_PASSWORD: '/auth/password/forgot',
    RESET_PASSWORD: '/auth/password/reset',
    TWO_FA_SETTINGS: '/auth/2fa/settings',
    TWO_FA_TOGGLE: '/auth/2fa/toggle',
    TWO_FA_SETUP: '/auth/2fa/setup',
    TWO_FA_VERIFY_SETUP: '/auth/2fa/verify-setup',
    TWO_FA_VERIFY: '/auth/2fa/verify',
    TWO_FA_DISABLE: '/auth/2fa/disable',
  },
  USERS: {
    ME: '/users/me',
    PUBLIC: (id: string) => `/users/${id}`,
    PREFERENCES: '/users/me/preferences',
    PROMPTS: '/users/me/prompts',
    AVAILABLE_PROMPTS: '/users/prompts',
    BLOCK: (userId: string) => `/users/${userId}/block`,
    UNBLOCK: (userId: string) => `/users/${userId}/block`,
    REPORT: (userId: string) => `/users/${userId}/report`,
    SYNC: '/users/sync',
    SUBMIT_APPEAL: '/users/me/appeal',
    MY_APPEALS: '/users/me/appeals',
  },
  PROFILES: {
    PHOTOS: '/users/me/photos',
    DELETE_PHOTO: (id: string) => `/users/me/photos/${id}`,
    REORDER_PHOTOS: '/users/me/photos/order',
    SET_PRIMARY_PHOTO: (id: string) => `/users/me/photos/${id}/primary`,
    VERIFY: '/profile/verification/request',
    VERIFICATION_STATUS: '/profile/verification',
  },
  MATCHING: {
    FEED: '/matching/feed',
    LIKE: (userId: string) => `/matching/like/${userId}`,
    PASS: (userId: string) => `/matching/pass/${userId}`,
    SUPER_LIKE: (userId: string) => `/matching/superlike/${userId}`,
    UNDO: '/matching/undo',
    REWIND: '/matching/rewind',
    MATCHES: '/matching/matches',
    UNMATCH: (matchId: string) => `/matching/matches/${matchId}`,
    LIKED_YOU: '/matching/liked-you',
    COMPATIBILITY: (userId: string) => `/matching/compatibility/${userId}`,
    BOOST: '/matching/boost',
    INCOGNITO: '/matching/incognito/toggle',
    PASSPORT: '/matching/passport',
    PHOTO_LIKE: (photoId: string) => `/matching/photos/${photoId}/like`,
    PHOTO_STATS: '/matching/photos/stats',
    PROFILE_VIEW: (userId: string) => `/matching/profile-view/${userId}`,
    PROFILE_VIEWERS: '/matching/profile-viewers',
    MOMENTS: '/matching/moments',
    MOMENTS_MINE: '/matching/moments/mine',
    MOMENT_VIEW: (id: string) => `/matching/moments/${id}/view`,
    MOMENT_DELETE: (id: string) => `/matching/moments/${id}`,
    SYNC: '/matching/sync',
    ICEBREAKERS: (userId: string) => `/matching/icebreakers/${userId}`,
    TOXICITY_CHECK: '/matching/toxicity-check',
    FAKE_PROFILE_CHECK: (userId: string) => `/matching/fake-profile-check/${userId}`,
    SCAM_CHECK: (userId: string) => `/matching/scam-check/${userId}`,
  },
  CHAT: {
    CONVERSATIONS: '/chat/conversations',
    MESSAGES: (conversationId: string) => `/chat/conversations/${conversationId}/messages`,
    SEND: (conversationId: string) => `/chat/conversations/${conversationId}/messages`,
    DELETE: (conversationId: string, messageId: string) => `/chat/conversations/${conversationId}/messages/${messageId}`,
    REACT: (conversationId: string, messageId: string) => `/chat/conversations/${conversationId}/messages/${messageId}/reactions`,
    READ: (conversationId: string) => `/chat/conversations/${conversationId}/read`,
    READ_RECEIPT: (conversationId: string, messageId: string) => `/chat/conversations/${conversationId}/messages/${messageId}/read`,
    TYPING: (conversationId: string) => `/chat/conversations/${conversationId}/typing`,
    SEARCH: '/chat/messages/search',
    SYNC: '/chat/sync',
  },
  CALLS: {
    START: '/calls/start',
    ANSWER: (callId: string) => `/calls/${callId}/answer`,
    REJECT: (callId: string) => `/calls/${callId}/reject`,
    END: (callId: string) => `/calls/${callId}/end`,
    HISTORY: '/calls/history',
    PAIR_HISTORY: (otherUserId: string) => `/calls/pair?otherUserId=${otherUserId}`,
  },
  MEDIA: {
    UPLOAD: '/media/upload',
    PRESIGNED_URL: '/media/presigned-url',
    GET: (id: string) => `/media/${id}`,
    DELETE: (id: string) => `/media/${id}`,
  },
  SUBSCRIPTIONS: {
    PLANS: '/payments/plans',
    SUBSCRIBE: '/payments/subscribe',
    CANCEL: '/payments/subscribe/cancel',
    UPGRADE: '/payments/subscribe/upgrade',
  },
  PAYMENTS: {
    INITIALIZE: '/payments/initialize',
    VERIFY: '/payments/verify',
    HISTORY: '/payments/history',
    REFUND: (transactionId: string) => `/payments/refund/${transactionId}`,
    WALLET: '/payments/wallet',
    TRANSACTIONS: '/payments/transactions',
    OPTIONS: '/payments/options',
  },
  NOTIFICATIONS: {
    LIST: '/notifications',
    PREFERENCES: '/notifications/preferences',
    MARK_READ: '/notifications/read',
    REGISTER: '/notifications/register',
  },
  SEARCH: {
    USERS: '/search/users',
    AUTOCOMPLETE: '/search/autocomplete',
  },
  SYNC: {
    VECTOR_CLOCK: '/sync/vector-clock',
  },
  CONTENT: {
    SAFETY_TIPS: '/content/safety-tips',
  },
  SUPPORT: {
    REPORT: '/support/report',
  },
};
