export const ENDPOINTS = {
  AUTH: {
    REGISTER: '/auth/register',
    LOGIN: '/auth/login',
    OTP_SEND: '/auth/otp/send',
    OTP_VERIFY: '/auth/otp/verify',
    REFRESH: '/auth/refresh',
    LOGOUT: '/auth/logout',
    FORGOT_PASSWORD: '/auth/password/forgot',
    RESET_PASSWORD: '/auth/password/reset',
  },
  USERS: {
    ME: '/users/me',
    PUBLIC: (id: string) => `/users/${id}`,
    PREFERENCES: '/users/me/preferences',
    BLOCK: (userId: string) => `/users/${userId}/block`,
    UNBLOCK: (userId: string) => `/users/${userId}/block`,
    REPORT: (userId: string) => `/users/${userId}/report`,
    SYNC: '/users/sync',
  },
  PROFILES: {
    PHOTOS: '/profile/photos',
    DELETE_PHOTO: (id: string) => `/profile/photos/${id}`,
    REORDER_PHOTOS: '/profile/photos/order',
    SET_PRIMARY_PHOTO: (id: string) => `/profile/photos/${id}/primary`,
    VERIFY: '/profile/verification/request',
    VERIFICATION_STATUS: '/profile/verification',
  },
  MATCHING: {
    FEED: '/matching/feed',
    LIKE: (userId: string) => `/matching/like/${userId}`,
    PASS: (userId: string) => `/matching/pass/${userId}`,
    SUPER_LIKE: (userId: string) => `/matching/superlike/${userId}`,
    UNDO: '/matching/undo',
    MATCHES: '/matching/matches',
    UNMATCH: (matchId: string) => `/matching/matches/${matchId}`,
    LIKED_YOU: '/matching/liked-you',
    COMPATIBILITY: (userId: string) => `/matching/compatibility/${userId}`,
    SYNC: '/matching/sync',
  },
  CHAT: {
    CONVERSATIONS: '/chat/conversations',
    MESSAGES: (conversationId: string) => `/chat/conversations/${conversationId}/messages`,
    SEND: (conversationId: string) => `/chat/conversations/${conversationId}/messages`,
    DELETE: (conversationId: string, messageId: string) => `/chat/conversations/${conversationId}/messages/${messageId}`,
    REACT: (conversationId: string, messageId: string) => `/chat/conversations/${conversationId}/messages/${messageId}/reactions`,
    READ: (conversationId: string) => `/chat/conversations/${conversationId}/read`,
    TYPING: (conversationId: string) => `/chat/conversations/${conversationId}/typing`,
    SEARCH: '/chat/messages/search',
    SYNC: '/chat/sync',
  },
  CALLS: {
    START: '/calls/start',
    ANSWER: (callId: string) => `/calls/${callId}/answer`,
    REJECT: (callId: string) => `/calls/${callId}/reject`,
    END: (callId: string) => `/calls/${callId}/end`,
    HISTORY: '/calls/history',
  },
  MEDIA: {
    UPLOAD: '/media/upload',
    PRESIGNED_URL: '/media/presigned-url',
    GET: (id: string) => `/media/${id}`,
    DELETE: (id: string) => `/media/${id}`,
  },
  SUBSCRIPTIONS: {
    PLANS: '/payments/plans',
    SUBSCRIBE: '/payments/subscribe',
    CANCEL: '/payments/subscribe/cancel',
    UPGRADE: '/payments/subscribe/upgrade',
  },
  PAYMENTS: {
    INITIALIZE: '/payments/initialize',
    VERIFY: '/payments/verify',
    HISTORY: '/payments/history',
    REFUND: (transactionId: string) => `/payments/refund/${transactionId}`,
  },
  NOTIFICATIONS: {
    LIST: '/notifications',
    PREFERENCES: '/notifications/preferences',
    MARK_READ: '/notifications/read',
    REGISTER: '/notifications/register',
  },
  SEARCH: {
    USERS: '/search/users',
    AUTOCOMPLETE: '/search/autocomplete',
  },
  SYNC: {
    VECTOR_CLOCK: '/sync/vector-clock',
  },
};
