export const ENDPOINTS = {
  AUTH: {
    REGISTER: '/auth/register',
    LOGIN: '/auth/login',
    OTP_SEND: '/auth/otp/send',
    OTP_VERIFY: '/auth/otp/verify',
    REFRESH: '/auth/refresh',
    LOGOUT: '/auth/logout',
    FORGOT_PASSWORD: '/auth/forgot-password',
    RESET_PASSWORD: '/auth/reset-password',
  },
  USERS: {
    ME: '/users/me',
    PUBLIC: (id: string) => `/users/${id}`,
    PREFERENCES: '/users/preferences',
    BLOCK: '/users/block',
    UNBLOCK: (userId: string) => `/users/block/${userId}`,
    REPORT: '/users/report',
  },
  PROFILES: {
    GET: (userId: string) => `/profiles/${userId}`,
    UPDATE: '/profiles',
    PHOTOS: '/profiles/photos',
    DELETE_PHOTO: (id: string) => `/profiles/photos/${id}`,
    REORDER_PHOTOS: '/profiles/photos/reorder',
    VERIFY: '/profiles/verify',
    INTERESTS: (userId: string) => `/profiles/${userId}/interests`,
    ADD_INTERESTS: '/profiles/interests',
  },
  MATCHING: {
    FEED: '/match/feed',
    LIKE: '/match/like',
    PASS: '/match/pass',
    SUPER_LIKE: '/match/super-like',
    UNDO: '/match/undo',
    MATCHES: '/match/matches',
    LIKED_YOU: '/match/liked-you',
    COMPATIBILITY: (userId: string) => `/match/compatibility/${userId}`,
    PREFERENCES: '/match/preferences',
  },
  CHAT: {
    CONVERSATIONS: '/chat/conversations',
    MESSAGES: (id: string) => `/chat/conversations/${id}/messages`,
    SEND: (id: string) => `/chat/conversations/${id}/messages`,
    DELETE: (id: string) => `/chat/messages/${id}`,
    REACT: (id: string) => `/chat/messages/${id}/react`,
    READ: (id: string) => `/chat/messages/${id}/read`,
    TYPING: (id: string) => `/chat/typing/${id}`,
    SEARCH: '/chat/search',
  },
  CALLS: {
    START: '/calls/start',
    ANSWER: '/calls/answer',
    REJECT: '/calls/reject',
    END: '/calls/end',
    HISTORY: '/calls/history',
    ICE_CANDIDATE: '/calls/ice-candidate',
  },
  MEDIA: {
    UPLOAD: '/media/upload',
    PRESIGNED_URL: '/media/presigned-url',
    GET: (id: string) => `/media/${id}`,
    DELETE: (id: string) => `/media/${id}`,
  },
  SUBSCRIPTIONS: {
    PLANS: '/subscriptions/plans',
    SUBSCRIBE: '/subscriptions/subscribe',
    CANCEL: '/subscriptions/cancel',
    UPGRADE: '/subscriptions/upgrade',
  },
  PAYMENTS: {
    INITIALIZE: '/payments/initialize',
    VERIFY: '/payments/verify',
    HISTORY: '/payments/history',
    REFUND: '/payments/refund',
  },
  NOTIFICATIONS: {
    LIST: '/notifications',
    PREFERENCES: '/notifications/preferences',
    MARK_READ: '/notifications/mark-read',
    QUIET_HOURS: '/notifications/quiet-hours',
  },
  SEARCH: {
    USERS: '/search/users',
    AUTOCOMPLETE: '/search/autocomplete',
  },
};
