export const SOCKET_EVENTS = {
  MESSAGE_SENT: 'message.sent',
  MESSAGE_RECEIVED: 'message.received',
  MESSAGE_READ: 'message.read',
  MESSAGE_DELETED: 'message.deleted',
  MESSAGE_REACTION: 'message.reaction',
  CONVERSATION_CREATED: 'conversation.created',
  CONVERSATION_UPDATED: 'conversation.updated',
  TYPING_START: 'typing.start',
  TYPING_STOP: 'typing.stop',
  USER_ONLINE: 'user.online',
  USER_OFFLINE: 'user.offline',
  USER_TYPING: 'user.typing',
  MATCH_CREATED: 'match.created',
  MATCH_MUTUAL: 'match.mutual',
  CALL_INITIATED: 'call.initiated',
  CALL_RINGING: 'call.ringing',
  CALL_ANSWERED: 'call.answered',
  CALL_REJECTED: 'call.rejected',
  CALL_ENDED: 'call.ended',
  SDP_OFFER: 'sdp.offer',
  SDP_ANSWER: 'sdp.answer',
  ICE_CANDIDATE: 'ice.candidate',
};
